language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: lBACdMTbi6OhyqBuqzyQtoZZuEXIg8RyCxmrzGJSvVI4AnBSOSXZqPw3FTRYSf2lunws5eSE58Rghh5vlGiKLwWcCktpznFw4sI0k1TRJwExuylWYqVAMdJnO1nqTNG0YWB7xGkBo9/XSF755kgt2fGvj/8LhIZFiN+6VSMg6IKMW8jloLxIYDdLnMOgXsdmjg6kPHR6Ho3tm8Z9pGfwgf03b+kr4t4d3r7XXQUIe+RDLX2HWYmJoa/kZci0l25WEs7vqlx1KrtCHkG8iQ7INAsUf7ykcqp1Bv9+1/wx++6Q66saM9AX3Zmq7nabvUZ1Tu1YwRD3apyepbiDMOhvUoXpYtHzXZvTA2yFNvx+vbqe9gJdFNWo9aj3OaBEQPFgRas3XUKO80JBuIonBBlR+pwDui0Pb39uORCTqzjaR1xbA9bRbaWRe3xk9xuQNsetLdV5sK0EXuZQydJqw4Nvgj5Ac/4c3GsFklSOLdtL7z532T+SyhWAttc3g796pLsXrcmZ73CgzET0DHGaouDEi9sKe998OLASKn9RaGscW9UPDpmAYV9rjZe23ted3gs4EhjVfMr80XUQu8tZz4xUnoF6a/ql14XcxgHHulKRj2CebHvjDeUgrlrGrcls6jBcdHoT2/z2A9uf2f5+GDrSzC6bGultCrrdsBCrdCzhVrU=
  app: english-rules-api
  on:
    repo: willnix86/english-rules-server
